name: Continous Deployment - Run tests and if succesfull deploy

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.0"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: SSH login on droplet and update CD app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SECRET }}
          port: ${{ secrets.PORT_SECRET }}
          username: ${{ secrets.USERNAME_SECRET }}
          key: ${{ secrets.CD_SECRET }}
          script: |
            cd /home/CD
            git pull origin main
            systemctl restart --now CD
